# This workflow will publish the package to NPM when commits are pushed to main
# It will only publish if the version in package.json has changed

name: Publish to NPM

on:
  push:
    branches:
      - main

jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      version-changed: ${{ steps.check.outputs.changed }}
      current-version: ${{ steps.get-version.outputs.version }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 2
      
      - name: Get current version
        id: get-version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
      
      - name: Check if version changed
        id: check
        run: |
          if git diff HEAD^ HEAD -- package.json | grep -q '"version"'; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "Version has changed, will publish to NPM"
          else
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "Version unchanged, skipping NPM publish"
          fi

  publish-npm:
    needs: check-version
    if: needs.check-version.outputs.version-changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      
      - uses: actions/setup-node@v6
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      
      - name: Install dependencies
        run: npm ci
      
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Create Git tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag "v${{ needs.check-version.outputs.current-version }}"
          git push origin "v${{ needs.check-version.outputs.current-version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
